name: anisurge
description: A free anime streaming app that lets you watch your favorite anime shows and movies anytime, anywhere.
version: 2.26.6+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  
  # State Management
  provider: ^6.1.2
  get: ^4.6.6
  
  # Navigation
  go_router: ^14.6.2
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_database: ^11.3.2
  firebase_analytics: ^11.3.8
  cloud_firestore: ^5.5.2
  google_sign_in: ^6.2.2
  
  # Networking
  http: ^1.2.2
  dio: ^5.7.0
  
  # Video Player
  video_player: ^2.9.2
  chewie: ^1.8.5
  wakelock_plus: ^1.2.11
  screen_brightness: ^1.0.1
  
  # Storage & Caching
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  package_info_plus: ^8.1.0
  device_info_plus: ^11.2.0
  
  # Local Notifications
  flutter_local_notifications: ^18.0.1
  
  # Image & Media
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  
  # JSON & Serialization
  json_annotation: ^4.9.0
  
  # WebView
  webview_flutter: ^4.10.0
  
  # Animations
  lottie: ^3.2.0
  flutter_animate: ^4.5.0
  
  # Platform
  flutter_platform_widgets: ^7.0.1
  
  # Windows support
  window_manager: ^0.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
